name: Publish Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate a changelog
      uses: orhun/git-cliff-action@v2
      id: changelog
      with:
        config: cliff.toml
        args: --latest --strip all
      env:
        OUTPUT: CHANGES.md
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Create a Release
      run: hub release create -F "${{ steps.changelog.outputs.changelog }}" "${{ env.RELEASE_VERSION }}"
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
